/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    events: Event;
    people: Person;
    teams: Team;
    fixtures: Fixture;
    sponsors: Sponsor;
    submissions: Submission;
    users: User;
    media: Media;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    fixtures: FixturesSelect<false> | FixturesSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    "home-page": HomePage;
    "chronik-page": ChronikPage;
    "vereinsheim-page": VereinsheimPage;
    "jugendfoerder-page": JugendfoerderPage;
    "faq-page": FaqPage;
    "legal-pages": LegalPage;
    "site-images": SiteImage;
    "site-settings": SiteSetting;
    navigation: Navigation;
    "contact-info": ContactInfo;
  };
  globalsSelect: {
    "home-page": HomePageSelect<false> | HomePageSelect<true>;
    "chronik-page": ChronikPageSelect<false> | ChronikPageSelect<true>;
    "vereinsheim-page":
      | VereinsheimPageSelect<false>
      | VereinsheimPageSelect<true>;
    "jugendfoerder-page":
      | JugendfoerderPageSelect<false>
      | JugendfoerderPageSelect<true>;
    "faq-page": FaqPageSelect<false> | FaqPageSelect<true>;
    "legal-pages": LegalPagesSelect<false> | LegalPagesSelect<true>;
    "site-images": SiteImagesSelect<false> | SiteImagesSelect<true>;
    "site-settings": SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    "contact-info": ContactInfoSelect<false> | ContactInfoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * Vereinsnews, Spielberichte und Ankündigungen. Erscheint unter /news.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Wird groß oben auf dem Artikel angezeigt.
   */
  title: string;
  /**
   * Wird automatisch aus der Überschrift erstellt. Nur ändern, wenn nötig.
   */
  slug: string;
  /**
   * 1 bis 2 Sätze. Wird in der News-Übersicht als Teaser angezeigt.
   */
  excerpt?: string | null;
  /**
   * Optionales Titelbild der News. Wird angezeigt, wenn gesetzt.
   */
  heroImage?: (number | null) | Media;
  /**
   * Der eigentliche Inhalt des Artikels.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Wer hat den Artikel geschrieben?
   */
  author?: (number | null) | Person;
  /**
   * Steht oben am Artikel und bestimmt die Reihenfolge in der News-Liste (neuestes zuerst). Ist mit jetzt vorbelegt.
   */
  publishedAt: string;
  /**
   * Mehrere möglich. Dient zur Filterung in der News-Liste.
   */
  tags?:
    | (
        | "spielbericht"
        | "verein"
        | "jugend"
        | "event"
        | "sponsoren"
        | "allgemein"
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle hochgeladenen Bilder. 'Alt-Text' ist Pflicht (Beschreibung für Screenreader & SEO). Bitte höchstens 4 MB pro Datei hochladen: größere Dateien werden vom Server abgewiesen. Handy-Fotos vorher verkleinern (z.B. in der Fotos-App teilen und 'Mittel' wählen).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Kurze Beschreibung des Bildinhalts. Pflicht! Wird für Screenreader und Google verwendet.
   */
  alt: string;
  /**
   * Optional. Wird unter dem Bild angezeigt.
   */
  caption?: string | null;
  /**
   * Optional. z.B. 'Foto: Max Mustermann'.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Vorstand, Trainer:innen, Spieler:innen. Über das Feld 'Funktion' wird die Person der richtigen Sektion auf der Website zugeordnet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * Wie soll die Rolle auf der Webseite stehen? z.B. '1. Vorstand', 'Sportlicher Leiter', 'Trainer A1'.
   */
  role: string;
  /**
   * Bestimmt, in welcher Sektion die Person auf der Webseite erscheint.
   */
  function:
    | "vorstand"
    | "sportleitung"
    | "jugendleitung"
    | "trainer"
    | "zeugwart"
    | "spieler"
    | "andere";
  /**
   * Portraitfoto. Optional, aber empfohlen.
   */
  photo?: (number | null) | Media;
  /**
   * Optional. Wird nur bei Vorstand/Trainer gezeigt.
   */
  phone?: string | null;
  email?: string | null;
  /**
   * Optional. Nötig für Trainer- und Spielerzuordnung zu einer Mannschaft.
   */
  team?: (number | null) | Team;
  /**
   * Kleinere Zahl = weiter oben in Listen.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle Teams (Senioren, Jugend, Volleyball etc.). BFV-/Fupa-IDs hier eintragen für Live-Daten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * z.B. '1. Herren', 'U19 Junioren', 'Bambini F3'.
   */
  name: string;
  /**
   * Wird automatisch aus dem Namen erstellt. Nur ändern, wenn nötig.
   */
  slug: string;
  sport:
    | "fussball"
    | "volleyball"
    | "gymnastik"
    | "ski"
    | "esport"
    | "schiedsrichter";
  /**
   * Grobe Einteilung für die Auflistung.
   */
  category?:
    | ("senioren" | "junioren" | "juniorinnen" | "bambini" | "allgemein")
    | null;
  /**
   * z.B. A1, B2, F3, Bambini.
   */
  ageGroup?: string | null;
  /**
   * Jahrgänge, z. B. 2006, 2007, 2008. Erscheinen im Mannschaftstitel.
   */
  birthYears?: string | null;
  /**
   * z.B. '2025/26'.
   */
  season?: string | null;
  /**
   * z.B. 'Landesliga'.
   */
  league?: string | null;
  /**
   * BFV-Daten verknüpfen, damit Live-Spielplan und Tabelle auf der Webseite erscheinen.
   */
  bfv?: {
    /**
     * 32-stellige BFV/DFB-Net ID, z.B. 016PMM83PG000000VV0AG811VUDIC8D7.
     */
    teamId?: string | null;
    /**
     * z.B. 'sv-n-lerchenau'.
     */
    slug?: string | null;
    /**
     * BFV-Wortlaut, z.B. 'Herren / Landesliga'.
     */
    spielklasse?: string | null;
    /**
     * Nur für Spielgemeinschaften, z.B. 'Spielgemeinschaft mit Fasanarie-Nord'.
     */
    partner?: string | null;
  };
  /**
   * Verknüpft das Team mit fupa.net, damit Kader und Spielerfotos angezeigt werden. Bei Jugend-SGs zusätzlich Hin- und Rückrunde eintragen. Die Saison im Slug wird zur Laufzeit automatisch auf die neueste auf fupa existierende Saison angehoben; ein Saisonwechsel erfordert also KEINE Pflege hier.
   */
  fupa?: {
    /**
     * Haupt-Slug, z.B. 'sv-nord-muenchen-lerchenau-m1-2026-27'. Saison-Suffix wird automatisch aktualisiert.
     */
    slug?: string | null;
    /**
     * Nur Jugend-SGs. z.B. 'sg-n-lerchenau-fasanerie-n-u19-1-autumn2025'. Saison-Suffix wird automatisch aktualisiert.
     */
    autumnSlug?: string | null;
    /**
     * Nur Jugend-SGs. z.B. 'sg-n-lerchenau-fasanerie-n-u19-1-spring2026'. Saison-Suffix wird automatisch aktualisiert.
     */
    springSlug?: string | null;
  };
  /**
   * Personen aus '2. Sport → Personen' auswählen (mehrere möglich).
   */
  trainers?: (number | Person)[] | null;
  /**
   * Optionale Vorstellung des Teams.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Wird auf den Mannschafts-Karten angezeigt, wenn kein BFV-Foto verknüpft ist (z. B. AH). Bei den Abteilungen Gymnastik, Volleyball und Ski ist das zugleich das große Bild oben auf der Abteilungsseite: Wird hier ein Foto hochgeladen, ersetzt es das mitgelieferte Standardbild.
   */
  photo?: (number | null) | Media;
  /**
   * z.B. BFV Spielplan, Tabelle, externe Seiten.
   */
  externalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kleinere Zahl = weiter oben in Listen.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vereinsfeste, Versammlungen und sonstige Termine. Erscheint unter /termine.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Name des Termins. z.B. 'Sommerfest 2026'.
   */
  title: string;
  /**
   * Wann startet die Veranstaltung?
   */
  startsAt: string;
  /**
   * Optional. Wann endet sie?
   */
  endsAt?: string | null;
  /**
   * z.B. 'Vereinsheim Lerchenau' oder Adresse.
   */
  location?: string | null;
  /**
   * Erscheint auf der Termine-Seite (Programm, Details). Listen und Absätze werden als Text angezeigt.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Foto oder Plakat zum Termin.
   */
  image?: (number | null) | Media;
  /**
   * Optional. Externer Link, z.B. zur Online-Anmeldung oder Eventseite. Erscheint als 'Zur Anmeldung'-Button.
   */
  ctaUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manuelle Spielansetzungen und Ergebnisse. Tipp: Live-Spielplan kommt automatisch vom BFV, hier nur Sonderfälle eintragen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures".
 */
export interface Fixture {
  id: number;
  /**
   * Welches Team spielt?
   */
  team: number | Team;
  /**
   * Name des gegnerischen Vereins.
   */
  opponent: string;
  kickoff: string;
  /**
   * z.B. 'Landesliga · Spieltag 20', 'Pokal'.
   */
  competition?: string | null;
  /**
   * z.B. 'Eschengarten' oder 'ASV Dachau Sportanlage'.
   */
  venue?: string | null;
  /**
   * Angekreuzt = wir spielen zuhause.
   */
  isHome?: boolean | null;
  /**
   * Erst nach dem Spiel ausfüllen.
   */
  result?: {
    homeGoals?: number | null;
    awayGoals?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Sponsorenlogos. 'Premium' = große Karte, 'Standard' = kleine Kachel. Erscheint unter /sponsoren.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  /**
   * PNG mit transparentem Hintergrund bevorzugt. Wird zentriert auf dunklem Hintergrund angezeigt.
   */
  logo: number | Media;
  /**
   * Optional. Vollständige URL inkl. https://.
   */
  url?: string | null;
  /**
   * Premium = große Karte, Standard = kleine Kachel.
   */
  tier: "premium" | "standard";
  /**
   * Kleinere Zahl = weiter oben.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nachrichten aus dem Kontaktformular. Häkchen 'Erledigt' setzen, wenn beantwortet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  name: string;
  email: string;
  phone: string;
  address: string;
  subject: string;
  message: string;
  /**
   * Häkchen setzen, wenn die Anfrage beantwortet ist.
   */
  handled?: boolean | null;
  /**
   * Nur für Vereins-Admins sichtbar — nicht öffentlich.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Login-Konten für das Admin-Panel. Login per Benutzername (E-Mail funktioniert weiterhin). Hier weitere Admins anlegen oder Passwörter ändern.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Wird oben rechts im Admin-Menü gezeigt.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "posts";
        value: number | Post;
      } | null)
    | ({
        relationTo: "events";
        value: number | Event;
      } | null)
    | ({
        relationTo: "people";
        value: number | Person;
      } | null)
    | ({
        relationTo: "teams";
        value: number | Team;
      } | null)
    | ({
        relationTo: "fixtures";
        value: number | Fixture;
      } | null)
    | ({
        relationTo: "sponsors";
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: "submissions";
        value: number | Submission;
      } | null)
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  author?: T;
  publishedAt?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  description?: T;
  image?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  function?: T;
  photo?: T;
  phone?: T;
  email?: T;
  team?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sport?: T;
  category?: T;
  ageGroup?: T;
  birthYears?: T;
  season?: T;
  league?: T;
  bfv?:
    | T
    | {
        teamId?: T;
        slug?: T;
        spielklasse?: T;
        partner?: T;
      };
  fupa?:
    | T
    | {
        slug?: T;
        autumnSlug?: T;
        springSlug?: T;
      };
  trainers?: T;
  description?: T;
  photo?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures_select".
 */
export interface FixturesSelect<T extends boolean = true> {
  team?: T;
  opponent?: T;
  kickoff?: T;
  competition?: T;
  venue?: T;
  isHome?: T;
  result?:
    | T
    | {
        homeGoals?: T;
        awayGoals?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  tier?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  address?: T;
  subject?: T;
  message?: T;
  handled?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Inhalte der Startseite (Hero, Schnellzugriff, Highlights).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Großer Begrüßungsbereich oben auf der Startseite.
   */
  hero: {
    /**
     * Kleiner Text über der Hauptüberschrift.
     */
    pretitle?: string | null;
    headlineLine1: string;
    headlineLine2: string;
    subline?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * Die Fotos oben im Kopfbereich und die Galerie weiter unten. Ohne Eintrag zeigt die Seite die mitgelieferten Bilder.
   */
  bilder?: {
    /**
     * Querformat-Fotos, die oben nacheinander eingeblendet werden. Reihenfolge per Drag-and-drop. Leer lassen heißt: mitgelieferte Bilder.
     */
    heroImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Die Fotowand unten auf der Startseite. Leer lassen heißt: mitgelieferte Bilder.
     */
    galerie?:
      | {
          image: number | Media;
          caption: string;
          sub?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Welche Blöcke werden auf der Startseite angezeigt? Häkchen entfernen = ausblenden.
   */
  sections?: {
    showNextMatch?: boolean | null;
    showFupa?: boolean | null;
    showNews?: boolean | null;
    showSports?: boolean | null;
    showEvents?: boolean | null;
    showSponsors?: boolean | null;
    showVereinsheim?: boolean | null;
    showLocation?: boolean | null;
    showMembershipCta?: boolean | null;
    showInstagram?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalte der Seite /chronik.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chronik-page".
 */
export interface ChronikPage {
  id: number;
  /**
   * Großes Bild oben auf der Chronik-Seite.
   */
  heroImage?: (number | null) | Media;
  /**
   * Kurzer Absatz unter der Überschrift.
   */
  intro?: string | null;
  /**
   * Hinweis: Die Vereinschronik wird aktuell im Code gepflegt. Dieses Feld wird derzeit nicht auf der Seite angezeigt.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalte der Seite /vereinsheim.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vereinsheim-page".
 */
export interface VereinsheimPage {
  id: number;
  heroImage?: (number | null) | Media;
  /**
   * Kurzer Absatz unter der Überschrift.
   */
  intro?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Mehrere Fotos vom Vereinsheim.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Optional.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalte der Seite /jugendfoerderverein.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jugendfoerder-page".
 */
export interface JugendfoerderPage {
  id: number;
  /**
   * Kurztext unter dem Seitentitel. Wenn leer, wird ein Standardtext angezeigt.
   */
  intro?: string | null;
  /**
   * Ansprache an Eltern und Freunde des SV Nord — was macht der Jugendförderverein?
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Konkrete Aktivitäten, die der Förderverein unterstützt. Erscheint als Liste.
   */
  supportBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  minAnnualFee?: number | null;
  /**
   * Pfad zur PDF-Beitrittserklärung. Standard liegt unter /downloads/.
   */
  formPdfUrl?: string | null;
  /**
   * Für Interessent:innen sichtbar.
   */
  primaryContactEmail?: string | null;
  boardMemberName?: string | null;
  boardRole?: string | null;
  boardContactEmail?: string | null;
  /**
   * Optional. Nur ausfüllen, wenn eine Direktspende-IBAN veröffentlicht werden soll.
   */
  iban?: string | null;
  /**
   * Veraltet. Bitte 'Hauptkontakt-E-Mail' verwenden. Feld bleibt nur für Datenkompatibilität.
   */
  contactEmail?: string | null;
  /**
   * Optionales Titelbild. Aktuell nicht eingeblendet — Reserve für spätere Gestaltung.
   */
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalte der Seite /faq.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  /**
   * Kurze Einleitung über dem Fragen-Akkordeon.
   */
  intro?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        /**
         * Fragen werden auf der Seite nach Kategorie gruppiert.
         */
        group?:
          | ("allgemein" | "mitgliedschaft" | "training" | "vereinsheim")
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pflichttexte für /impressum und /datenschutz.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  /**
   * Pflichtangaben gemäß § 5 TMG. Erscheint unter /impressum.
   */
  impressumBody: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * DSGVO-Erklärung. Vor Änderungen am besten Rechtsbeistand fragen. Erscheint unter /datenschutz.
   */
  datenschutzBody: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Einzelne Bilder auf Unterseiten: die drei Fotos der U8.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images".
 */
export interface SiteImage {
  id: number;
  /**
   * Die drei Fotos im U8-Bereich.
   */
  u8?: {
    trainerteam?: (number | null) | Media;
    loewen?: (number | null) | Media;
    tiger?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Vereinsname und SEO-Angaben (Beschreibung, Teilen-Bild), global verwendet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Wird global verwendet (z.B. im Footer).
   */
  name: string;
  tagline?: string | null;
  description?: string | null;
  ogImage?: (number | null) | Media;
  social?:
    | {
        platform: "instagram" | "facebook" | "youtube" | "x" | "tiktok";
        /**
         * Vollständige URL inkl. https://.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Links der Fußzeile. Das Hauptmenü oben ist bewusst fest im Code hinterlegt, damit es am Handy und im Browser identisch aufgebaut ist.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Einträge in der Reihenfolge wie sie erscheinen sollen.
   */
  header?:
    | {
        label: string;
        /**
         * z.B. '/news', '/fussball' oder vollständige URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Spalten der Fußzeile. Pro Spalte: Überschrift + Links.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Adressen, Kontakt und Öffnungszeiten (Footer und /kontakt).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  /**
   * Mehrere möglich (Postanschrift, Vereinsheim …).
   */
  addresses?:
    | {
        /**
         * z.B. 'Postanschrift', 'Vereinsheim Eschengarten'.
         */
        label: string;
        street: string;
        postalCode: string;
        city: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Wird auf /kontakt angezeigt, wenn gesetzt. Leer lassen, wenn keine zentrale Nummer veröffentlicht werden soll.
   */
  phone?: string | null;
  email: string;
  /**
   * Für Mitgliedsbeiträge und Spenden.
   */
  iban?: string | null;
  openingHours?:
    | {
        /**
         * z.B. 'Mo bis Fr', 'Sa', 'So'.
         */
        day: string;
        /**
         * z.B. '17:00 bis 22:00' oder 'geschlossen'.
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Die 'src'-URL aus dem Google-Maps iframe-Embed-Code einfügen.
   */
  mapEmbedSrc?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        pretitle?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        subline?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  bilder?:
    | T
    | {
        heroImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        galerie?:
          | T
          | {
              image?: T;
              caption?: T;
              sub?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        showNextMatch?: T;
        showFupa?: T;
        showNews?: T;
        showSports?: T;
        showEvents?: T;
        showSponsors?: T;
        showVereinsheim?: T;
        showLocation?: T;
        showMembershipCta?: T;
        showInstagram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chronik-page_select".
 */
export interface ChronikPageSelect<T extends boolean = true> {
  heroImage?: T;
  intro?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vereinsheim-page_select".
 */
export interface VereinsheimPageSelect<T extends boolean = true> {
  heroImage?: T;
  intro?: T;
  body?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jugendfoerder-page_select".
 */
export interface JugendfoerderPageSelect<T extends boolean = true> {
  intro?: T;
  body?: T;
  supportBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  minAnnualFee?: T;
  formPdfUrl?: T;
  primaryContactEmail?: T;
  boardMemberName?: T;
  boardRole?: T;
  boardContactEmail?: T;
  iban?: T;
  contactEmail?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  intro?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        group?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  impressumBody?: T;
  datenschutzBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images_select".
 */
export interface SiteImagesSelect<T extends boolean = true> {
  u8?:
    | T
    | {
        trainerteam?: T;
        loewen?: T;
        tiger?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  ogImage?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        postalCode?: T;
        city?: T;
        id?: T;
      };
  phone?: T;
  email?: T;
  iban?: T;
  openingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  mapEmbedSrc?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
